### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by hmoffatt** [qdewaghe/compile-commands#2]
I'm getting an error running this in python 3.9.

```
$ find . -name compile_commands.json
./projects/.../.../compile_commands.json
./projects/.../.../compile_commands.json
./projects/.../compile_commands.json
./projects/.../compile_commands.json

$ compile-commands --merge --dir projects
Traceback (most recent call last):
  File "/home/hamish/.local/bin/compile-commands", line 8, in <module>
    sys.exit(main())
  File "/home/hamish/.local/lib/python3.9/site-packages/src/compile_commands.py", line 370, in main
    data = [dict(t) for t in {tuple(d.items()) for d in data}]
  File "/home/hamish/.local/lib/python3.9/site-packages/src/compile_commands.py", line 370, in <setcomp>
    data = [dict(t) for t in {tuple(d.items()) for d in data}]
TypeError: unhashable type: 'list'

$ compile-commands --dir projects/...
Traceback (most recent call last):
  File "/home/hamish/.local/bin/compile-commands", line 8, in <module>
    sys.exit(main())
  File "/home/hamish/.local/lib/python3.9/site-packages/src/compile_commands.py", line 370, in main
    data = [dict(t) for t in {tuple(d.items()) for d in data}]
  File "/home/hamish/.local/lib/python3.9/site-packages/src/compile_commands.py", line 370, in <setcomp>
    data = [dict(t) for t in {tuple(d.items()) for d in data}]
TypeError: unhashable type: 'list'
```

**Comment by hmoffatt** [comment]
With the latest code I now have

```
$ compile-commands --dir . --merge
Traceback (most recent call last):
  File "/home/hamish/.local/bin/compile-commands", line 8, in <module>
    sys.exit(main())
  File "/home/hamish/.local/lib/python3.9/site-packages/src/compile_commands.py", line 373, in main
    args.files = get_compile_dbs(args.dir)
  File "/home/hamish/.local/lib/python3.9/site-packages/src/compile_commands.py", line 202, in get_compile_dbs
    return [p for p in paths if Path(p).parent.parts[-1] != Path(directory).parts[-1]]
  File "/home/hamish/.local/lib/python3.9/site-packages/src/compile_commands.py", line 202, in <listcomp>
    return [p for p in paths if Path(p).parent.parts[-1] != Path(directory).parts[-1]]
IndexError: tuple index out of range
```

Although if I leave out `--dir .` it seems to work.

**Comment by qdewaghe** [comment]
Forgot an `os.path.abspath()` while refactoring, should work again with relative paths.

**Comment by hmoffatt** [comment]
Thanks, merging is working fine now.
